# Generated by Django 3.0.5 on 2020-05-04 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='equipamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamento.EquipamentosFixos'),
        ),
    ]
