# Generated by Django 3.0.5 on 2020-05-04 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
                ('edataC', models.DateField()),
                ('estatus', models.CharField(max_length=20)),
                ('efornecedor', models.CharField(max_length=100)),
                ('earea', models.CharField(max_length=50)),
                ('eqtd', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'equipamento',
            },
        ),
        migrations.CreateModel(
            name='EquipamentosFixos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
                ('emanutencao', models.BooleanField()),
                ('efornecedor', models.CharField(max_length=100)),
                ('estatus', models.CharField(max_length=20)),
                ('edataC', models.DateField()),
                ('edataM', models.DateField()),
                ('earea', models.CharField(max_length=20)),
                ('eqtd', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'equipamentosFixos',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('regiao', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fornecedor',
            },
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamento.Area')),
            ],
            options={
                'db_table': 'salas',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=100)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamento.Area')),
            ],
            options={
                'db_table': 'responsavel',
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('edata', models.DateField()),
                ('horario', models.TimeField()),
                ('dias', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('equipamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamento.Equipamento')),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamento.Fornecedor')),
            ],
            options={
                'db_table': 'manutencao',
            },
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('horarioF', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('equipamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamento.EquipamentosFixos')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamento.Responsavel')),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamento.Salas')),
            ],
            options={
                'db_table': 'alocacao',
            },
        ),
    ]
